export enum UserRole {
  ADMIN = 'ADMIN',
  BUYER = 'BUYER',
  SELLER = 'SELLER',
  SHIPPER = 'SHIPPER',
}

export enum SubAdminRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  TECHNICIAN = 'TECHNICIAN',
  WAREHOUSE_MANAGER = 'WAREHOUSE_MANAGER',
  FINANCE_STAFF = 'FINANCE_STAFF',
  CONTENT_MANAGER = 'CONTENT_MANAGER',
  CUSTOMER_SUPPORT = 'CUSTOMER_SUPPORT',
}

export enum BuyerType {
  INDIVIDUAL = 'INDIVIDUAL',
  WHOLESALER = 'WHOLESALER',
  BUSINESS = 'BUSINESS',
}

export enum VehicleType {
  MOTORBIKE = 'MOTORBIKE',
  VAN = 'VAN',
  TRUCK = 'TRUCK',
  COLD_TRUCK = 'COLD_TRUCK',
}

export enum ShipmentStatus {
  PENDING = 'PENDING',
  ASSIGNED = 'ASSIGNED',
  PICKED_UP = 'PICKED_UP',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  RETURNED = 'RETURNED',
}
export enum ProductCategory {
  FRUITS = 'FRUITS',
  VEGETABLES = 'VEGETABLES',
  GRAINS = 'GRAINS',
  DAIRY = 'DAIRY',
  MEAT = 'MEAT',
  SEAFOOD = 'SEAFOOD',
  BEVERAGES = 'BEVERAGES',
  OTHER = 'OTHER',
}

export enum ProductUnit {
  KG = 'KG',
  GRAM = 'GRAM',
  TON = 'TON',
  LITER = 'LITER',
  ML = 'ML',
  PIECE = 'PIECE',
  DOZEN = 'DOZEN',
  LOT = 'LOT',
  BOX = 'BOX',
  BUNCH = 'BUNCH',
}

export enum ProductStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  DISCONTINUED = 'DISCONTINUED',
}

export enum OrderStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum OrderType {
  RETAIL = 'RETAIL',
  WHOLESALE = 'WHOLESALE',
  PRE_ORDER = 'PRE_ORDER',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum PaymentMethod {
  CREDIT_CARD = 'CREDIT_CARD',
  DEBIT_CARD = 'DEBIT_CARD',
  STRIPE = 'STRIPE',
  MOMO = 'MOMO',
  BANK_TRANSFER = 'BANK_TRANSFER',
  COD = 'COD',
  ONLINE = 'ONLINE',
}

export enum PayoutMethodEnum {
  BANK_TRANSFER = 'BANK_TRANSFER',
  STRIPE = 'STRIPE',
  MOMO = 'MOMO',
  CASH = 'CASH',
}

export enum PayoutStatusEnum {
  PENDING = 'PENDING',
  PAID = 'PAID',
  FAILED = 'FAILED',
}

export enum NotificationChannel {
  INTERNAL = 'internal',
  EMAIL = 'email',
  SMS = 'sms',
  PUSH = 'push',
}

export enum NotificationType {
  // System notifications
  SYSTEM_ALERT = 'SYSTEM_ALERT',
  MAINTENANCE = 'MAINTENANCE',
  UPDATE = 'UPDATE',

  // Order notifications
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_CONFIRMED = 'ORDER_CONFIRMED',
  ORDER_SHIPPED = 'ORDER_SHIPPED',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  ORDER_REFUNDED = 'ORDER_REFUNDED',

  // Payment notifications
  PAYMENT_SUCCEEDED = 'PAYMENT_SUCCEEDED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_REFUNDED = 'PAYMENT_REFUNDED',

  // Inventory notifications
  LOW_STOCK = 'LOW_STOCK',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  RESTOCKED = 'RESTOCKED',

  // User notifications
  ACCOUNT_VERIFIED = 'ACCOUNT_VERIFIED',
  ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  LOGIN_ALERT = 'LOGIN_ALERT',

  // Seller notifications
  SELLER_APPROVED = 'SELLER_APPROVED',
  SELLER_REJECTED = 'SELLER_REJECTED',
  NEW_ORDER = 'NEW_ORDER',
  NEW_REVIEW = 'NEW_REVIEW',

  // Buyer notifications
  ORDER_STATUS_UPDATE = 'ORDER_STATUS_UPDATE',
  SHIPPING_UPDATE = 'SHIPPING_UPDATE',
  PROMOTION = 'PROMOTION',
  COUPON_EXPIRING = 'COUPON_EXPIRING',

  // Custom/Other
  CUSTOM = 'CUSTOM',
}

export enum NotificationPriority {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum NotificationStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  READ = 'READ',
}
